### PR TITLE
Add warmup exercises

### PR DESCRIPTION
**Pull request by janmasrovira**
This pr adds a number of very easy exercises. These exercises are supposed to be algorithmically trivial, but can still useful for the user to get accustomed to the language syntax and features.

### CODE REVIEW

**Comment by janmasrovira** [comment]
when I run `make pre-commit` locally, the formatting gets messed up and the exercise solutions no longer are displayed properly

**Comment by paulcadman** [comment]
@janmasrovira do you think it's a good idea to add some of these exercises to https://github.com/anoma/juvix-eth-workshop/blob/main/exercises/Exercises.juvix ? Maybe it'd be good to split the workshop exercises into, warm-up and more advanced?

**Comment by janmasrovira** [comment]
> @janmasrovira do you think it's a good idea to add some of these exercises to https://github.com/anoma/juvix-eth-workshop/blob/main/exercises/Exercises.juvix ? Maybe it'd be good to split the workshop exercises into, warm-up and more advanced?

I think that would be a good idea

**Comment by jonaprieto** [comment]
> when I run `make pre-commit` locally, the formatting gets messed up and the exercise solutions no longer are displayed properly

Let me look into this.

**Comment by jonaprieto** [comment]
> , the formatting gets messed up and the exercise solutions no longer are displayed properly

You forgot to add a blank line after the `!!! tip` and maybe the spaces. Anyway, I fixed this.

**Review by jonaprieto — APPROVED** [review]

**Comment by janmasrovira** [comment]
> > , the formatting gets messed up and the exercise solutions no longer are displayed properly
> 
> You forgot to add a blank line after the `!!! tip` and maybe the spaces. Anyway, I fixed this.

If it renders properly, shouldn't the formatter respect that? I must be missing something... I'd like to understand exactly what, or I'm going to run into more problems like this in the future

**Pull request merged**
